### PR TITLE
boom

### PR DESCRIPTION
**Pull request by giftedl**
extension to #9

### CODE REVIEW

**Comment by lilysoftpaws** [comment]
Hey, thanks for the updated contribution!

Just a quick note—could you please remove the package-lock.json file from your PR? We don't commit this file to our repo to avoid cross-platform dependency issues. Once that's sorted, we'll be happy to merge your changes.

Stay Snuggly!
*The Snuggles team*

**Comment by UwUAroze** [comment]
Hey, thanks for the review request @lilyvxv!

@DeveloLongScript Upon further inspection of your error handling, I think improvements should be made — specifically to the database `PingError`.

If a user executes `/ping` and it fails, it will leave them staring at a cute spinny loading icon. At first, they'll be happy, satisfied by the cute spinny... But then, it'll never end. They'll be sitting there, dazzled and confused, waiting for the spinny to finish its spin, but to no avail. Our user will sit here for the rest of eternity, until they will die.

Needless to say, this behaviour is ideal. A better solution could be to replace the loading icon with "Failed to ping", or something along those lines, if the database ping fails. Once that's also sorted, we'll be happy to merge your changes.

Stay Snuggly!
*The Snuggles team*

**Review by UwUAroze — CHANGES_REQUESTED** [review]
Hey, thanks for the review request @lilyvxv!

@DeveloLongScript Upon further inspection of your error handling, I think improvements should be made — specifically to the database `PingError`.

If a user executes `/ping` and it fails, it will leave them staring at a cute spinny loading icon. At first, they'll be happy, satisfied by the cute spinny... But then, it'll never end. They'll be sitting there, dazzled and confused, waiting for the spinny to finish its spin, but to no avail. Our user will sit here for the rest of eternity, until they die.

Needless to say, this behaviour is unideal. A better solution could be to replace the loading icon with "Failed to ping", or something along those lines, if the database ping fails. Once that's also sorted, we'll be happy to merge your changes.

Stay Snuggly!
*The Snuggles team*

**Comment by giftedl** [comment]
> [we **CANNOT** have them dazzling. No- No!](https://github.com/UwUAroze/Snuggles/pull/10/commits/9f38b59cd9477eae19e750b5aca216c8c463f629)

wake up [imaginary] user
@lilyvxv 

Stay in existence™!
*dvelo*

**Review by lilysoftpaws — CHANGES_REQUESTED** [review]
Hey, thanks for the additional changes @DeveloLongScript!

Though I've noted a few issues that need addressing before we can merge:

- The `PingError` message is far too vague. While it might initially seem like a minor hiccup, it soon becomes a source of endless confusion. With the database ping potentially failing for various reasons and no specific details provided, users are left in a state of perpetual puzzlement, unable to diagnose the issue. It’s like being stuck in an endless loop of ambiguity, where finding a solution feels like a never-ending quest. To break free from this confusion, including the original stack trace in the error message would provide the crucial details needed for proper debugging.

- Additionally, the `PingError` is being caught and swallowed by the try-catch block, so it's not providing useful feedback to users. Consider enhancing error handling to ensure custom errors are properly handled and provide meaningful information.

- Finally, the message ("There was an error /*...*/ database setup correctly?") thrown by the `DeploymentError` is completely off. The deployment code never interacts with the database; it communicates with the Discord API to register our slash commands. This could seriously confuse users as they frantically check their database in and out for problems, only to find none. The error message is masking the real cause!

Once these are all sorted, we'll be happy to merge your changes.

Stay Snuggly!
*The Snuggles team*

**Comment by giftedl** [comment]
> Hey, thanks for the additional changes @DeveloLongScript!
> 
> Though I've noted a few issues that need addressing before we can merge:
> 
> * The `PingError` message is far too vague. While it might initially seem like a minor hiccup, it soon becomes a source of endless confusion. With the database ping potentially failing for various reasons and no specific details provided, users are left in a state of perpetual puzzlement, unable to diagnose the issue. It’s like being stuck in an endless loop of ambiguity, where finding a solution feels like a never-ending quest. To break free from this confusion, including the original stack trace in the error message would provide the crucial details needed for proper debugging.
> * Additionally, the `PingError` is being caught and swallowed by the try-catch block, so it's not providing useful feedback to users. Consider enhancing error handling to ensure custom errors are properly handled and provide meaningful information.
> * Finally, the message ("There was an error /_..._/ database setup correctly?") thrown by the `DeploymentError` is completely off. The deployment code never interacts with the database; it communicates with the Discord API to register our slash commands. This could seriously confuse users as they frantically check their database in and out for problems, only to find none. The error message is masking the real cause!
> 
> Once these issues are resolved, we’ll be good to go!
> 
> Stay Snuggly! _The Snuggles team_

1. `extends Error` automaticly adds a stack trace if i believe
2. fair
3. i think i mixed up my files.. that was defintely supposed to be somewhere else

i think this is too much effort i can chew lol
ill keep going though

**Comment by pauliesnug** [comment]
10/10

**Comment by giftedl** [comment]
I don't have enough time to finish this PR - maybe you guys could come up with something similar.

**Pull request closed without merging**
